---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes
      changed_when: false

    - name: Install iptables
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - iptables
        - iptables-persistent


  roles:
    - {role: 'wireguard', tags: 'wireguard'}
