---
- name: Check if wg0-server.conf already exists
  stat:
    path: /etc/wireguard/wg0.conf
  register: wg0_conf

- name: Generate private and public keys for the client and server
  shell: umask 077; wg genkey | tee {{ item }}.private | wg pubkey > {{ item }}.public
  register: key_files
  loop: "{{ range(0, clients) | list }}"
  #with_sequence: start=0 end={{ clients }}
  when: wg0_conf is not defined or wg0_conf.stat.exists == false


- name: Register private key file contents
  shell: cat {{ item }}.private
  register: private_key_files
  loop: "{{ range(0, clients) | list }}"
  #with_sequence: start=0 end={{ clients }}
  when: wg0_conf is not defined or wg0_conf.stat.exists == false

- name: Register public key file contents
  shell: cat {{ item }}.public
  register: public_key_files
  loop: "{{ range(0, clients) | list }}"
  #with_sequence: start=0 end={{ clients }}
  when: wg0_conf is not defined or wg0_conf.stat.exists == false

- name: Generate directories for client configs
  file:
    path: "~/wg_clients/client_{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0600
  loop: "{{ range(1, clients) | list }}"
  #with_sequence: start=1 end={{ clients }}
  when: wg0_conf is not defined or wg0_conf.stat.exists == false

- name: Generate client configs
  template:
    src: "templates/client.conf.j2"
    dest: "~/wg_clients/client_{{ item }}/wg0-client.conf"
    owner: root
    group: root
    mode: 0600
  loop: "{{ range(1, clients) | list }}"
  #with_sequence: start=1 end={{ clients }}
  when: wg0_conf is not defined or wg0_conf.stat.exists == false

- name: Stop any running Wireguard service
  systemd:
    name: wg-quick@wg0.service
    state: stopped
  when: wg0_conf is not defined or wg0_conf.stat.exists == false

# Should happen last among the config file creations, so if the process 
# is interrupted we will re-generate everything (the existence of the 
# server config is used to determine whether to generate the server and 
# client config files)
- name: Generate server config
  template:
    src: "templates/server.conf.j2"
    dest: "/etc/wireguard/wg0.conf"
    owner: root
    group: root
    mode: 0600
  when: wg0_conf.stat is not defined or wg0_conf.stat.exists == false

- name: Print server public key
  debug:
    var: public_key_files.results[0].stdout
  when: wg0_conf.stat is not defined or wg0_conf.stat.exists == false

- name: Enable wireguard interface
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started

- name: Register the clients on the vpn server
  shell: wg set wg0 peer {{ public_key_files.results[item|int].stdout }} allowed-ips {{ vpn_network }}.{{item|int + 1}}/32
  loop: "{{ range(1, clients) | list }}"
  #with_sequence: start=1 end={{ clients }}
  when: wg0_conf is not defined or wg0_conf.stat.exists == false

- name: Restart the VPN service to save changes
  systemd:
    name: wg-quick@wg0.service
    state: restarted
  when: wg0_conf is not defined or wg0_conf.stat.exists == false