---
- name: Install wireguard and other prequisites on the server
  import_tasks: 'install_wireguard.yml'
  tags: install_wireguard

- name: Generate client keys and enable wireguard interface
  import_tasks: 'generate_keys.yml'
  tags: generate_keys

- name: Set up nat and firewall rules
  import_tasks: 'nat_and_firewall.yml'
  tags: nat_and_firewall

- name: Download client configs
  import_tasks: 'download_configs.yml'
  tags: download_configs

- name: Add another client - will only run if the add_client tag is specified
  import_tasks: 'additional_client.yml'
  vars:
    new_client: newclient
    new_client_ip: 10.200.200.12
  tags: ['never', 'add_client']
